# -*- coding: utf-8 -*-
"""TiagoSouza_pymongo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s09mK3IDTnMyihFZ81LP9NDtRg_LYsog
"""

# install and start server
#!apt install mongodb >log
#!service mongodb start

from pymongo import MongoClient
import pandas as pd

client = MongoClient()

read_csv = pd.read_csv("discentes-2022.csv", delimiter=";")
#read_csv.head()

csv_to_dict = read_csv.to_dict(orient = "records")
#csv_to_dict

db = client["db_discentes2022"]
#print(db)

collection = db['coll_discentes2022']
#print(collection)

collection.insert_many(csv_to_dict)
#print(collection.find_one())

#Exemplos de consultas (queries): (Só descomentar para testar)
#1. Listar todos os alunos que ingressaram por meio do SiSU

for document in collection.find({"forma_ingresso":"SiSU"}):
    print(document)

#2. Listar todos os alunos que ingressaram no mestrado

#for document in collection.find({"nivel_ensino":"MESTRADO"}):
#    print(document)

#3. Listar todos os alunos de uma unidade gestora

#for document in collection.find({"nome_unidade_gestora":"CENTRO DE TECNOLOGIA"}):
#    print(document)

#4. Listar todos os alunos regulares

#for document in collection.find({"tipo_discente":"REGULAR"}):
#    print(document)

#5. Listar todos os alunos pelo status (cancelado, ativo, etc.)

#for document in collection.find({"status":"CANCELADO"}):
#    print(document)